#!/bin/bash

name="lucastorterotot scripts"

echo "Installing $name..."

instal_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
bin_dir=$instal_dir/bin/

if [[ $PATH = *$bin_dir* ]] || [[ $(grep -l "$name" ~/.bashrc) = ~/.bashrc ]]
then
    echo 'It seems like you already have installed this!'
    echo 'Not changing anything.'
else
    if [[ $instal_dir = $HOME* ]]
    then
        instal_dir=~${instal_dir#$HOME}
        bin_dir=$instal_dir/bin/
    fi
    echo "" >> ~/.bashrc
    echo "# --- add $name ---" >> ~/.bashrc
    echo "export PATH=$bin_dir:"'$PATH' >> ~/.bashrc
    echo ". $instal_dir/bash_completion" >> ~/.bashrc
    echo "Installation completed."
fi
